  # Datasource Configuration
spring.datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: "jdbc:sqlserver://${DB_HOST:localhost}:${DB_POSTGRES_PORT:5432};databaseName=${DB_POSTGRES_DB:userappdb}"
    username: ${DB_POSTGRES_USER:postgres}
    password: ${DB_POSTGRES_PASSWORD:password}
spring.jpa:
        # Show or not log for each sql query
        show-sql: false
        # Hibernate settings are prefixed with spring.jpa.hibernate.*
        hibernate:
            ddl-auto: validate # validate | update | create | create-drop
            dialect: org.hibernate.dialect.SQLServer2017Dialect
            format_sql: true
---

#This profile include in memory database configuration and disable flyway
spring:
  profiles: test
spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:MY_APP;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:db/migration/test/init_tests.sql';
    username: sa
    password:
spring.jpa:
    hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
flyway.enabled : false
#flyway.schemas : PUBLIC

# Flyway configuartion
flyway.baseline-on-migrate: true
